### ISSUE TITLE
Logo no display in main page

### ISSUE THREAD

**Issue by Arsfrezy** [Simpliz/client#4]
![image](https://github.com/Simpliz/client/assets/126679005/f7146340-e5eb-4a42-bd7b-cb4ebde874e3)

**Comment by stackpan** [comment]
Ah i see, i'll fix it later. Or you can fix it if you want

**Comment by stackpan** [comment]
Fixed in [fcc1cdf](https://github.com/Simpliz/client/commit/fcc1cdf1565ea8f5ae613b85e15b537da3fb9fdd)
